# Generated by Django 4.1.7 on 2023-03-10 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
        migrations.AddField(
            model_name='entry',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='entry',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
