# Generated by Django 4.1.6 on 2023-02-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('+', 'income'), ('-', 'spend')], default='-', max_length=1),
        ),
    ]
