# Generated by Django 4.1.7 on 2023-03-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('log', '0003_alter_entry_content_type_alter_entry_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
