# Generated by Django 4.1.6 on 2023-02-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_category_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
