# Generated by Django 4.1.7 on 2023-03-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_entry_content_type_alter_entry_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
