# Generated by Django 4.1.6 on 2023-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_entry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'Euros'), ('RUB', 'Russian Rubles'), ('KZT', 'Khazakh Tenge')], default=3, max_length=3),
        ),
    ]
