# Generated by Django 4.1.6 on 2023-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_entry_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='entry',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
