# Generated by Django 4.1.7 on 2023-03-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_delete_user_alter_entry_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#d3d3d3', max_length=7),
        ),
    ]
