# Generated by Django 4.1.7 on 2023-03-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_usercategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'User category', 'verbose_name_plural': 'User categories'},
        ),
    ]
