# Generated by Django 4.1.7 on 2023-03-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_alter_usercategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
