# Generated by Django 4.1.7 on 2023-03-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_remove_category_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]
