# Generated by Django 4.1.7 on 2023-03-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'User category', 'verbose_name_plural': 'User categories'},
        ),
    ]
