# Generated by Django 4.1.7 on 2023-03-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowance',
            field=models.FloatField(default=0),
        ),
    ]
