# Generated by Django 4.1.7 on 2023-03-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_allowance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allowance',
            new_name='budget',
        ),
    ]
